all:pyrbmview.py plotwin.py simpleplotwin.py

pyrbmview.py: rbm_gui.ui
	pyuic4 -x rbm_gui.ui > pyrbmview.py
plotwin.py: plotwin.ui
	pyuic4 plotwin.ui > plotwin.py
simpleplotwin.py: simpleplotwin.ui
	pyuic4 simpleplotwin.ui > simpleplotwin.py
