# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbm_gui.ui'
#
# Created: Tue Jun 22 12:39:34 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_pyRBMView(object):
    def setupUi(self, pyRBMView):
        pyRBMView.setObjectName("pyRBMView")
        pyRBMView.resize(823, 478)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyRBMView.sizePolicy().hasHeightForWidth())
        pyRBMView.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(pyRBMView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setAutoFillBackground(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.mdiArea = QtGui.QMdiArea(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        pyRBMView.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pyRBMView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuRBM = QtGui.QMenu(self.menubar)
        self.menuRBM.setObjectName("menuRBM")
        pyRBMView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(pyRBMView)
        self.statusbar.setObjectName("statusbar")
        pyRBMView.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(pyRBMView)
        self.toolBar.setObjectName("toolBar")
        pyRBMView.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        pyRBMView.insertToolBarBreak(self.toolBar)
        self.actionClose = QtGui.QAction(pyRBMView)
        self.actionClose.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionClose.setObjectName("actionClose")
        self.actionConnect = QtGui.QAction(pyRBMView)
        self.actionConnect.setObjectName("actionConnect")
        self.actionGrid = QtGui.QAction(pyRBMView)
        self.actionGrid.setObjectName("actionGrid")
        self.actionStack = QtGui.QAction(pyRBMView)
        self.actionStack.setObjectName("actionStack")
        self.actionShowSubWin = QtGui.QAction(pyRBMView)
        self.actionShowSubWin.setObjectName("actionShowSubWin")
        self.actionUpdate_All = QtGui.QAction(pyRBMView)
        self.actionUpdate_All.setObjectName("actionUpdate_All")
        self.actionContinuous_Updates = QtGui.QAction(pyRBMView)
        self.actionContinuous_Updates.setCheckable(True)
        self.actionContinuous_Updates.setObjectName("actionContinuous_Updates")
        self.actionSave_Config = QtGui.QAction(pyRBMView)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionClose)
        self.menuWindow.addAction(self.actionSave_Config)
        self.menuWindow.addAction(self.actionGrid)
        self.menuWindow.addAction(self.actionStack)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionUpdate_All)
        self.menuRBM.addAction(self.actionContinuous_Updates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRBM.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.toolBar.addAction(self.actionContinuous_Updates)
        self.toolBar.addAction(self.actionGrid)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect)

        self.retranslateUi(pyRBMView)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), pyRBMView.close)
        QtCore.QObject.connect(self.actionGrid, QtCore.SIGNAL("activated()"), self.mdiArea.tileSubWindows)
        QtCore.QObject.connect(self.actionStack, QtCore.SIGNAL("activated()"), self.mdiArea.cascadeSubWindows)
        QtCore.QObject.connect(self.treeWidget, QtCore.SIGNAL("itemDoubleClicked(QTreeWidgetItem*,int)"), self.actionShowSubWin.trigger)
        QtCore.QMetaObject.connectSlotsByName(pyRBMView)

    def retranslateUi(self, pyRBMView):
        pyRBMView.setWindowTitle(QtGui.QApplication.translate("pyRBMView", "pyRBMView", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("pyRBMView", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("pyRBMView", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRBM.setTitle(QtGui.QApplication.translate("pyRBMView", "RBM", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("pyRBMView", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("pyRBMView", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("pyRBMView", "&Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrid.setText(QtGui.QApplication.translate("pyRBMView", "&Tile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrid.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStack.setText(QtGui.QApplication.translate("pyRBMView", "St&ack", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowSubWin.setText(QtGui.QApplication.translate("pyRBMView", "showSubWin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_All.setText(QtGui.QApplication.translate("pyRBMView", "Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_All.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContinuous_Updates.setText(QtGui.QApplication.translate("pyRBMView", "&Continuous Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContinuous_Updates.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("pyRBMView", "&Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setShortcut(QtGui.QApplication.translate("pyRBMView", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    pyRBMView = QtGui.QMainWindow()
    ui = Ui_pyRBMView()
    ui.setupUi(pyRBMView)
    pyRBMView.show()
    sys.exit(app.exec_())

